server:
  port: 8080

#   mybatisPlus 性能分析差价开关,自定义
performance:
  enable: true

spring:
  thymeleaf:
    # 发布时改成true
    cache: false
  mvc:
    static-path-pattern: /static/**
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/aoeai-leet-code-study-record?useSSL=false&jdbcCompliantTruncation=false&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: test
    password: 123456
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.aoeai.lcsr.dao.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    #  不重启刷新XML文件，开发开启，生产关闭 3.0.6 已关闭
    #    refresh: true
    db-config:
      db-type: mysql
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker
      #     逻辑已删除值,(逻辑删除下有效)
      logic-delete-value: 1
      #     逻辑未删除值,(逻辑删除下有效)
      logic-not-delete-value: 0
      #     字段策略 ignore:"忽略判断",not_null:"非 NULL 判断"),not_empty:"非空判断"
      field-strategy: not_null

#logging:
#  level:
#    com:
#      aoeai:
#        lcsr:
#          dao:
#            mapper: debug

#logback:
#  logdir: ~/test
#  appname: lcsr